version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Ducks" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\Ducks" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
# - dotnet publish "src\ducks" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts\Ducks
test_script:
- dotnet test "test\UnitTests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
